defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: cimg/node:18.17.0
version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - restore_cache:
          keys:
            - source-{{ .Branch }}-{{ .Revision }}
            - source-{{ .Branch }}-
            - source-

      - checkout

      - save_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
          paths:
            - "~/repo"
  install:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Install Dependencies"
          command: yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Test"
          command: yarn test
  build:
    <<: *defaults
    steps:
      - restore_cache:
          key: source-{{ .Branch }}-{{ .Revision }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: "Build app"
          command: yarn build
      - persist_to_workspace:
          root: ~/repo
          paths:
            - dist
            - package.json
  deploy:
    <<: *defaults
    docker:
      - image: circleci/python:latest
    steps:
      - attach_workspace:
          at: ~/repo
      - run: sudo pip install awscli
      - run:
          name: "Deploy to S3"
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              aws s3 sync dist/ s3://${PRODUCTION_BUCKET} --delete
            fi
workflows:
  version: 2
  build_and_test:
    jobs:
      - checkout_code
      - install:
          requires:
            - checkout_code
      - test:
          requires:
            - install
      - build:
          requires:
            - install
      - deploy:
          requires:
            - test
            - build
